### ISSUE TITLE
Use WordPress way to perform HTTP requests

### ISSUE THREAD

**Issue by pawelkmpt** [FastComments/fastcomments-wordpress-plugin#2]
I was reviewing code of the plugin and have suggestion to replace this long `curl` setup with `wp_remote_request()` which is preferred way of performing HTTP requests in WordPress.

Find more:
* https://developer.wordpress.org/reference/functions/wp_remote_request/
* https://developer.wordpress.org/reference/functions/wp_remote_post/

https://github.com/FastComments/fastcomments-wordpress-plugin/blob/7ce4d93e3ee7093bdd7aa63b9c0332dd0a66af02/core/FastCommentsWordPressIntegration.php#L144-L183

**Comment by winrid** [comment]
@pawelkmpt Thank you! Should have known WP has a way to handle this.

**Comment by winrid** [comment]
@pawelkmpt Fixed in 3.9.5
